export const mockUser = {
  id: "demo-user-001",
  phone: "9999900001",
  name: "Rajesh Kumar",
  email: "rajesh.demo@rivanreality.com",
  address: "Plot 22, Jubilee Hills, Hyderabad",
  kyc_status: "verified",
  is_admin: false,
  created_at: new Date().toISOString(),
};

export const mockProperties = [
  {
    id: "prop-1",
    name: "Rivan Greens",
    category: "Open Plots",
    location: "Shamshabad, Hyderabad",
    starting_price: 2775000,
    size: "200-500 sq yards",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    ],
    description: "Premium plotted development with wide roads, avenue plantation, and clear title.",
    plot_number: "P-005",
    survey_number: "SY-No 234/3",
    facing: "Multiple",
    road_width: "40 ft",
    availability: "Available",
    featured: true,
    amenities: ["Avenue Plantation", "Underground Drainage", "Street Lights"],
    approvals: ["RERA Registered", "HMDA Layout"],
    nearby: ["Shamshabad Airport - 20 min", "ORR - 5 min"],
    highlights: "HMDA approved · Ready to build",
  },
  {
    id: "prop-2",
    name: "Rivan Heritage Villas",
    category: "Villas",
    location: "Kokapet, Hyderabad",
    starting_price: 14500000,
    size: "2400-3800 sq ft",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750"],
    videoUrl: "https://res.cloudinary.com/dzisksq78/video/upload/v1780939161/villa_1_ltxt2q.mp4",
    description: "Elegant villas with landscaped courts, premium finishes, and a warm family-first layout.",
    plot_number: "V-03",
    survey_number: "SY-No 89/2",
    facing: "Multiple",
    road_width: "30 ft",
    availability: "Available",
    featured: true,
    amenities: ["Clubhouse", "Private Garden", "EV Charging", "Power Backup"],
    approvals: ["RERA Registered", "GHMC Approved"],
    nearby: ["Financial District - 10 min", "ORR - 8 min"],
    highlights: "Villa community · Video walkthrough available",
  },
  {
    id: "prop-3",
    name: "Rivan Skyline Towers",
    category: "Flats",
    location: "Gachibowli, Hyderabad",
    starting_price: 8500000,
    size: "1450-2200 sq ft",
    image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80",
    images: ["https://images.unsplash.com/photo-1502672023488-70e25813eb80"],
    description: "Contemporary apartments with skyline views and practical family layouts.",
    plot_number: "F-1204",
    survey_number: "SY-No 11/1",
    facing: "East / West",
    road_width: "60 ft",
    availability: "Available",
    featured: false,
    amenities: ["Pool", "Gym", "Kids Play Area"],
    approvals: ["RERA Registered"],
    nearby: ["HITEC City - 12 min", "Metro - 8 min"],
    highlights: "City living · Ready inventory",
  },
];

export const mockFeaturedProperties = mockProperties.filter((p) => p.featured);

export const mockNotifications = [
  {
    id: "notif-1",
    title: "Welcome to Rivan Reality",
    body: "Explore premium properties with the demo data loaded locally.",
    type: "welcome",
    read: false,
    created_at: new Date().toISOString(),
  },
];
